package orm

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib" // PostgreSQL-Treiber (pgx, database/sql)
)

type pgDriver struct {
	dsn string
	yb  bool
}

// Postgres verbindet mit PostgreSQL (pgx-Pool).
func Postgres(dsn string) Driver { return pgDriver{dsn: dsn} }

// Yugabyte verbindet mit YugabyteDB (YSQL, PG-Wire-Protokoll). Die DSN
// sollte die regional nahen Endpunkte enthalten.
func Yugabyte(dsn string) Driver { return pgDriver{dsn: dsn, yb: true} }

func (p pgDriver) connect() (*sql.DB, dialect, error) {
	which := "PostgreSQL"
	if p.yb {
		which = "YugabyteDB"
	}
	sdb, err := sql.Open("pgx", p.dsn)
	if err != nil {
		return nil, nil, fmt.Errorf("orm: %s öffnen: %w", which, err)
	}
	sdb.SetMaxOpenConns(10)
	sdb.SetConnMaxIdleTime(5 * time.Minute)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := sdb.PingContext(ctx); err != nil {
		_ = sdb.Close()
		return nil, nil, fmt.Errorf("orm: %s erreichen: %w", which, err)
	}
	d := pgDialect{}
	if p.yb {
		d.n = "yugabyte"
	} else {
		d.n = "postgres"
	}
	return sdb, d, nil
}

type pgDialect struct{ n string }

func (d pgDialect) name() string { return d.n }

func (pgDialect) rebind(query string) string { return rebindDollar(query) }

func (pgDialect) tableColumns(q queryer, table string) ([]string, error) {
	rows, err := q.QueryContext(bgCtx(),
		`SELECT column_name FROM information_schema.columns
		 WHERE table_name = ? AND table_schema = current_schema()`, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var cols []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		cols = append(cols, name)
	}
	return cols, rows.Err()
}

func (pgDialect) columnType(k colKind) string {
	switch k {
	case kInt, kBool:
		return "BIGINT"
	case kFloat:
		return "DOUBLE PRECISION"
	case kBlob:
		return "BYTEA"
	case kJSON:
		return "JSONB"
	default:
		return "TEXT"
	}
}

func (pgDialect) zeroLiteral(k colKind) string {
	switch k {
	case kInt, kBool, kFloat:
		return "0"
	case kBlob:
		return `'\x'`
	case kJSON:
		return "'null'" // gültiges JSON(B) — '' wäre beim Lesen ein Parse-Fehler
	default:
		return "''"
	}
}

func (pgDialect) autoPK() string { return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" }

func (pgDialect) limitAll() string { return "ALL" }

func (pgDialect) forUpdate() string { return " FOR UPDATE" }

func (pgDialect) partitionClause() string { return ` PARTITION BY LIST ("geo")` }

// partitionSQL: eine LIST-Partition je deklarierter Region plus eine
// DEFAULT-Partition für 'local' und noch nicht deklarierte Geos. Auf YB
// binden Placement/Tablespaces später an die Regions-Partitionen (Stufe 2).
func (pgDialect) partitionSQL(table string, regions []string) []string {
	stmts := []string{fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %q PARTITION OF %q DEFAULT`,
		table+"_geo_default", table)}
	for _, r := range regions {
		stmts = append(stmts, fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %q PARTITION OF %q FOR VALUES IN ('%s')`,
			table+"_geo_"+r, table, strings.ReplaceAll(r, "'", "''")))
	}
	return stmts
}

func (pgDialect) dualWriteTriggerSQL(table, pk string) []string {
	fn := "ormpp_dw_" + table
	// Eine Funktion + ein Zeilen-Trigger für alle drei Operationen;
	// DROP+CREATE macht die Anlage idempotent (PG kennt kein IF NOT EXISTS).
	return []string{
		fmt.Sprintf(`CREATE OR REPLACE FUNCTION %q() RETURNS trigger AS $ormpp$
BEGIN
  IF TG_OP = 'DELETE' THEN
    INSERT INTO ormpp_dualwrite_queue (tbl, pk, op, changed_at)
    VALUES ('%s', OLD.%q, 'delete', to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
    RETURN OLD;
  END IF;
  INSERT INTO ormpp_dualwrite_queue (tbl, pk, op, changed_at)
  VALUES ('%s', NEW.%q, 'upsert', to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
  RETURN NEW;
END $ormpp$ LANGUAGE plpgsql`, fn, table, pk, table, pk),
		fmt.Sprintf(`DROP TRIGGER IF EXISTS %q ON %q`, fn+"_t", table),
		fmt.Sprintf(`CREATE TRIGGER %q AFTER INSERT OR UPDATE OR DELETE ON %q
			FOR EACH ROW EXECUTE FUNCTION %q()`, fn+"_t", table, fn),
	}
}
